# Generated by Django 4.0 on 2021-12-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationHash', models.CharField(max_length=100)),
                ('stationName', models.CharField(max_length=100)),
                ('currentDispatcherName', models.CharField(max_length=100)),
                ('currentDispatcherId', models.IntegerField(max_length=10)),
                ('currentDispatcherFrom', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
