# Generated by Django 4.0 on 2021-12-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenery',
            name='currentDispatcherId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='stationHash',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
