# Generated by Django 4.0 on 2021-12-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_scenery_currentdispatcherid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenery',
            name='dispatcherHistory',
            field=models.JSONField(default='{}'),
        ),
    ]
