# Generated by Django 4.0 on 2021-12-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_scenery_dispatcherhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenery',
            name='currentDispatcherId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scenery',
            name='currentDispatcherName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
